// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"main.go/types"
)

// NewMockDNSClient creates a new instance of MockDNSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSClient {
	mock := &MockDNSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDNSClient is an autogenerated mock type for the DNSClient type
type MockDNSClient struct {
	mock.Mock
}

type MockDNSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSClient) EXPECT() *MockDNSClient_Expecter {
	return &MockDNSClient_Expecter{mock: &_m.Mock}
}

// GetDMARCData provides a mock function for the type MockDNSClient
func (_mock *MockDNSClient) GetDMARCData(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetDMARCData")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSClient_GetDMARCData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDMARCData'
type MockDNSClient_GetDMARCData_Call struct {
	*mock.Call
}

// GetDMARCData is a helper method to define mock.On call
//   - s string
func (_e *MockDNSClient_Expecter) GetDMARCData(s any) *MockDNSClient_GetDMARCData_Call {
	return &MockDNSClient_GetDMARCData_Call{Call: _e.mock.On("GetDMARCData", s)}
}

func (_c *MockDNSClient_GetDMARCData_Call) Run(run func(s string)) *MockDNSClient_GetDMARCData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDNSClient_GetDMARCData_Call) Return(s1 string, err error) *MockDNSClient_GetDMARCData_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockDNSClient_GetDMARCData_Call) RunAndReturn(run func(s string) (string, error)) *MockDNSClient_GetDMARCData_Call {
	_c.Call.Return(run)
	return _c
}

// GetDNSData provides a mock function for the type MockDNSClient
func (_mock *MockDNSClient) GetDNSData(context1 context.Context, s string, s1 string) types.DNSData {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetDNSData")
	}

	var r0 types.DNSData
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) types.DNSData); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(types.DNSData)
	}
	return r0
}

// MockDNSClient_GetDNSData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDNSData'
type MockDNSClient_GetDNSData_Call struct {
	*mock.Call
}

// GetDNSData is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockDNSClient_Expecter) GetDNSData(context1 any, s any, s1 any) *MockDNSClient_GetDNSData_Call {
	return &MockDNSClient_GetDNSData_Call{Call: _e.mock.On("GetDNSData", context1, s, s1)}
}

func (_c *MockDNSClient_GetDNSData_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockDNSClient_GetDNSData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSClient_GetDNSData_Call) Return(dNSData types.DNSData) *MockDNSClient_GetDNSData_Call {
	_c.Call.Return(dNSData)
	return _c
}

func (_c *MockDNSClient_GetDNSData_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) types.DNSData) *MockDNSClient_GetDNSData_Call {
	_c.Call.Return(run)
	return _c
}
